version: '2.13'
name: bookstore

services:
  postgres:
    image: 'postgres:13'
    container_name: 'pg'
    expose:
      - "5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=spring_rest'
  backend:
    build: 
      context: ./back-bookstore
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring_rest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  frontend:
    build: 
      context: ./front-bookstore
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

     
   